INSERT INTO users (id, email, password, time_zone)
VALUES (1, 'user1@test.com', 'pw', 'UTC'),
    (2, 'user2@test.com', 'pw', 'Europe/Madrid'),
    (3, 'user3@test.com', 'pw', 'UTC'),
    (4, 'user4@test.com', 'pw', 'America/New_York'),
    (5, 'user5@test.com', 'pw', 'UTC')
INSERT INTO profiles (
        id,
        username,
        profilename,
        description,
        profile_type,
        image
    )
VALUES (
        1,
        'user1',
        'GM_Master',
        'Game master profile',
        'TABLETOP',
        'img1.png'
    ),
    (
        2,
        'user2',
        'ShadowRogue',
        'Stealth player',
        'WRITTEN',
        'img2.png'
    ),
    (
        3,
        'user3',
        'ArcaneMage',
        'Spellcaster',
        'WRITTEN',
        'img3.png'
    ),
    (
        4,
        'user4',
        'TankKnight',
        'Frontliner',
        'TABLETOP',
        'img4.png'
    ),
    (
        5,
        'user5',
        'SupportCleric',
        'Healer',
        'TABLETOP',
        'img5.png'
    )
INSERT INTO campaign (
        id,
        owner_name,
        members,
        name,
        image,
        description,
        system,
        themes,
        campaign_type,
        status,
        max_players,
        communication,
        language,
        day_week,
        time_zone,
        frequency,
        duration,
        location
    )
VALUES (
        1,
        'GM_Master',
        ARRAY ['GM_Master','ShadowRogue','ArcaneMage'],
        'Sharn Campaign',
        'sharn.png',
        'Intrigue in the city of towers',
        'D&D 5e',
        ARRAY ['intrigue','noir','politics'],
        'TABLETOP',
        'ACTIVE',
        5,
        'Discord',
        'English',
        'Saturday',
        'Europe/Madrid',
        'Weekly',
        '3h',
        'Online'
    ),
    (
        2,
        'ShadowRogue',
        ARRAY ['ShadowRogue','ArcaneMage'],
        'Secret Ops',
        'ops.png',
        'Covert missions campaign',
        'Cyberpunk',
        ARRAY ['stealth','heist'],
        'WRITTEN',
        'OPEN',
        4,
        'Forum',
        'English',
        'Flexible',
        'UTC',
        'Async',
        'Variable',
        'Online'
    )
INSERT INTO sheets (
        id,
        name,
        schema,
        image,
        is_template,
        is_public,
        template_id,
        campaign_id,
        profile_id
    )
VALUES (
        1,
        'Kael',
        '[{"name":"dex","value":18}]'::jsonb,
        'kael.png',
        FALSE,
        TRUE,
        NULL,
        1,
        2
    ),
    (
        2,
        'Lyra',
        '[{"name":"int","value":17}]'::jsonb,
        'lyra.png',
        FALSE,
        TRUE,
        NULL,
        1,
        3
    ),
    (
        3,
        'Template Warrior',
        '[{"name":"str","value":15}]'::jsonb,
        'warrior.png',
        TRUE,
        TRUE,
        NULL,
        NULL,
        1
    ),
    (
        4,
        'Thorin',
        '[{"name":"con","value":16}]'::jsonb,
        'thorin.png',
        FALSE,
        FALSE,
        3,
        1,
        4
    )
INSERT INTO campaign_request(id, profile_id, campaign_id, message, status)
VALUES (1, 2, 1, 'Let me join!', 0),
    (2, 3, 1, 'Mage looking for party', 1),
    (3, 4, 1, 'Tank ready', 2),
    (4, 5, 2, 'Support here', 0)
INSERT INTO posts(
        id,
        type,
        title,
        tags,
        content,
        author_profile_id,
        author_character_id,
        author_character_name,
        author_character_image,
        campaign_id,
        parent_post_id,
        created_at,
        is_ooc,
        is_dm,
        media_urls,
        is_edited,
        updated_at,
        is_pinned,
        is_locked,
        rol_type
    )
VALUES (
        1,
        'THREAD_START',
        'Arrival',
        ARRAY ['intro','city'],
        '<p>Welcome to Sharn</p>',
        1,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NOW(),
        FALSE,
        TRUE,
        '[]'::jsonb,
        FALSE,
        NULL,
        TRUE,
        FALSE,
        'TABLETOP'
    ),
    (
        2,
        'THREAD_START',
        'Secret Mission',
        ARRAY ['secret'],
        '<p>Hidden quest</p>',
        1,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NOW(),
        FALSE,
        TRUE,
        '[]'::jsonb,
        FALSE,
        NULL,
        FALSE,
        FALSE,
        'TABLETOP'
    ),
    (
        3,
        'REPLY',
        NULL,
        ARRAY ['rp'],
        '<p>Kael sneaks</p>',
        2,
        1,
        'Kael',
        'kael.png',
        1,
        1,
        NOW(),
        FALSE,
        FALSE,
        '[]'::jsonb,
        FALSE,
        NULL,
        FALSE,
        FALSE,
        'WRITTEN'
    ),
    (
        4,
        'REPLY',
        NULL,
        ARRAY ['rp'],
        '<p>Lyra observes</p>',
        3,
        2,
        'Lyra',
        'lyra.png',
        1,
        1,
        NOW(),
        FALSE,
        FALSE,
        '[]'::jsonb,
        TRUE,
        NOW(),
        FALSE,
        FALSE,
        'WRITTEN'
    ),
    (
        5,
        'THREAD_START',
        'Locked Thread',
        ARRAY ['system'],
        '<p>Closed discussion</p>',
        1,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NOW(),
        FALSE,
        TRUE,
        '[]'::jsonb,
        FALSE,
        NULL,
        FALSE,
        TRUE,
        'TABLETOP'
    )
INSERT INTO post_visible_characters(post_id, character_id)
VALUES (2, 1),
    (2, 2),
    (4, 2),
    (5, 4)