spring.application.name=rolesync
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=hola
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
# Configuración JWT
app.jwtSecret=EstaEsUnaClaveSecretaMuyLargaParaQueFuncioneElAlgoritmoHS256
app.jwtExpirationMs=86400000 
# (24 horas)

spring.datasource.url=jdbc:postgresql://dpg-d7fqqci8qa3s73dnp36g-a.frankfurt-postgres.render.com:5432/rolesync_db
# postgresql://rolesync_db_user:DXNadMsBED3NG1YgiagarVNhIIrXyamF@dpg-d7fqqci8qa3s73dnp36g-a.frankfurt-postgres.render.com/rolesync_db
spring.datasource.username=rolesync_db_user
spring.datasource.password=DXNadMsBED3NG1YgiagarVNhIIrXyamF
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect