spring.application.name=rolesync
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=hola
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

#Deploy configuration
#Database (from environment)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

# #Local configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/rolesyncdb
# spring.datasource.username=postgres
# spring.datasource.password=1234
# spring.datasource.driver-class-name=org.postgresql.Driver

# # Configuración JWT
# app.jwtSecret=EstaEsUnaClaveSecretaMuyLargaParaQueFuncioneElAlgoritmoHS256
# app.jwtExpirationMs=86400000 
# # (24 horas)
# #CONFIG DB Param Local
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
