name: Codacy Coverage Reporter

on:
  push:
    branches:
      - "**"

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    environment: Backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/site/jacoco/jacoco.xml
