name: Build, Tag and Deploy

permissions:
  contents: write

env:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
    TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}  

on:
  push:
    branches:
      - main
      - backend-develop

jobs:
  build-tag-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set version tag
      - name: Generate version
        id: version
        run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      # 3. Create Git tag
      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.VERSION }}

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "$DOCKER_USERNAME"
          password: "$DOCKER_PASSWORD"

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/rolesync:${{ steps.version.outputs.VERSION }} .
          docker tag "$DOCKER_USERNAME"/rolesync:${{ steps.version.outputs.VERSION }} \
                     "$DOCKER_USERNAME"/rolesync:latest

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          docker push "$DOCKER_USERNAME"/rolesync:${{ steps.version.outputs.VERSION }}
          docker push "$DOCKER_USERNAME"/rolesync:latest

      # 7. Trigger Render deploy
      - name: Deploy to Render
        run: |
          curl -X POST "$DEPLOY_HOOK_URL"
